<template>
  <div>switch的文档</div>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
  <p>switch的文档</p>
</template>